# Generated by Django 5.1.3 on 2024-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedu_user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
