# Generated by Django 5.1.3 on 2024-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_weedu_user_avatar_weedu_user_expirience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weedu_user',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
    ]
