# Generated by Django 5.1.3 on 2024-11-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_weedu_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weedu_user',
            old_name='expirience',
            new_name='experience',
        ),
    ]
